-- SIMPLE_REVIEW 캠페인 타입 도입: 카테고리, 서브타입, LINE 트리거 enum 값 확장.
ALTER TYPE "CampaignCategory" ADD VALUE 'SIMPLE_REVIEW';
ALTER TYPE "CampaignSubType" ADD VALUE 'LIPS';
ALTER TYPE "CampaignSubType" ADD VALUE 'ATCOSME';
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_APPLICATION_APPLIED';
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_APPLICATION_APPROVED';
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_APPLICATION_REJECTED';
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_SUBMITTED';
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_APPROVED';
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_REJECTED';
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_DEADLINE_REMINDER';
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_REJECTION_REMINDER';
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_SETTLEMENT_COMPLETED';
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_CAMPAIGN_COMPLETED';
