-- SNS_INSIGHT_APPROVED 트리거 완전 제거.
-- Postgres 는 enum 값을 직접 DROP 할 수 없으므로 새 enum 을 만들어 교체.

-- 1) 해당 enum 값을 사용하는 row 삭제 (템플릿 시드 row + 발송 로그).
DELETE FROM "LineDispatchLog" WHERE "triggerKey" = 'SNS_INSIGHT_APPROVED';
DELETE FROM "LineMessageTemplate" WHERE "triggerKey" = 'SNS_INSIGHT_APPROVED';

-- 2) SNS_INSIGHT_APPROVED 를 뺀 새 enum 생성.
CREATE TYPE "LineTriggerKey_new" AS ENUM (
  'SNS_APPLICATION_APPLIED',
  'SNS_APPLICATION_APPROVED',
  'SNS_APPLICATION_REJECTED',
  'SNS_APPLICATION_SHIPPED',
  'SNS_APPLICATION_DELIVERED',
  'SNS_APPLICATION_RECEIPT_CONFIRMED',
  'SNS_POST_SUBMITTED',
  'SNS_POST_DEADLINE_REMINDER',
  'SNS_POST_APPROVED',
  'SNS_POST_REJECTED',
  'SNS_POST_REJECTION_REMINDER',
  'SNS_INSIGHT_SUBMITTED',
  'SNS_INSIGHT_REMINDER',
  'SNS_INSIGHT_OVERDUE_REMINDER',
  'SNS_SETTLEMENT_COMPLETED',
  'SNS_CAMPAIGN_COMPLETED',
  'FAKE_PURCHASE_APPLICATION_APPLIED',
  'FAKE_PURCHASE_APPLICATION_APPROVED',
  'FAKE_PURCHASE_APPLICATION_REJECTED',
  'FAKE_PURCHASE_ORDER_SUBMITTED',
  'FAKE_PURCHASE_REVIEW_SUBMITTED',
  'FAKE_PURCHASE_REVIEW_APPROVED',
  'FAKE_PURCHASE_REVIEW_REJECTED',
  'FAKE_PURCHASE_REVIEW_DEADLINE_REMINDER',
  'FAKE_PURCHASE_SETTLEMENT_COMPLETED',
  'FAKE_PURCHASE_CAMPAIGN_COMPLETED',
  'SIMPLE_REVIEW_APPLICATION_APPLIED',
  'SIMPLE_REVIEW_APPLICATION_APPROVED',
  'SIMPLE_REVIEW_APPLICATION_REJECTED',
  'SIMPLE_REVIEW_APPLICATION_SHIPPED',
  'SIMPLE_REVIEW_APPLICATION_DELIVERED',
  'SIMPLE_REVIEW_APPLICATION_RECEIPT_CONFIRMED',
  'SIMPLE_REVIEW_SUBMITTED',
  'SIMPLE_REVIEW_APPROVED',
  'SIMPLE_REVIEW_REJECTED',
  'SIMPLE_REVIEW_DEADLINE_REMINDER',
  'SIMPLE_REVIEW_REJECTION_REMINDER',
  'SIMPLE_REVIEW_SETTLEMENT_COMPLETED',
  'SIMPLE_REVIEW_CAMPAIGN_COMPLETED'
);

-- 3) 컬럼 타입 교체.
ALTER TABLE "LineMessageTemplate"
  ALTER COLUMN "triggerKey" TYPE "LineTriggerKey_new"
  USING "triggerKey"::text::"LineTriggerKey_new";
ALTER TABLE "LineDispatchLog"
  ALTER COLUMN "triggerKey" TYPE "LineTriggerKey_new"
  USING "triggerKey"::text::"LineTriggerKey_new";

-- 4) 기존 enum 삭제 후 신규 enum 이름을 원래 이름으로.
DROP TYPE "LineTriggerKey";
ALTER TYPE "LineTriggerKey_new" RENAME TO "LineTriggerKey";
