-- SIMPLE_REVIEW 배송 프로세스 도입: SNS 배송 흐름과 동일한 3개 트리거 enum 추가.
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_APPLICATION_SHIPPED';
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_APPLICATION_DELIVERED';
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_APPLICATION_RECEIPT_CONFIRMED';
