/** J-WIN 어드민 계약 타입 재노출 — 화면·hook은 이 파일에서만 가져온다. */
export {
  AdminCampaignListItemSchema,
  AdminCampaignListSchema,
  AdminCampaignCreateSchema,
  AdminCampaignPatchSchema,
  AdminCampaignDetailSchema,
  AdminBrandAccountSchema,
  AdminBrandAccountListSchema,
  AdminBrandAccountCreateSchema,
  AdminPrizeSchema,
  AdminPrizeListSchema,
  AdminPrizePatchSchema,
  AdminPrizeCreateSchema,
  AdminPostTemplateSchema,
  AdminPostTemplateListSchema,
  AdminPostTemplateCreateSchema,
  AdminWinnerSchema,
  AdminWinnerListSchema,
  AdminShippingSchema,
  AdminFulfillmentPatchSchema,
} from "@jsure/jwin-shared";
export type {
  AdminCampaignListItem,
  AdminCampaignList,
  AdminCampaignCreate,
  AdminCampaignPatch,
  AdminCampaignDetail,
  AdminBrandAccount,
  AdminBrandAccountList,
  AdminBrandAccountCreate,
  AdminPrize,
  AdminPrizeList,
  AdminPrizePatch,
  AdminPrizeCreate,
  AdminPostTemplate,
  AdminPostTemplateList,
  AdminPostTemplateCreate,
  AdminWinner,
  AdminWinnerList,
  AdminShipping,
  AdminFulfillmentPatch,
} from "@jsure/jwin-shared";
