-- 마감 경과 독촉 리마인더 트리거 3종 추가.
-- enum 값 추가는 additive 라 기존 row·구 코드에 영향이 없다.
-- 새 값을 쓰는 template row 는 운영자가 어드민에서 본문을 작성할 때 생긴다.
ALTER TYPE "LineTriggerKey" ADD VALUE 'SNS_POST_OVERDUE_REMINDER' AFTER 'SNS_POST_DEADLINE_REMINDER';
ALTER TYPE "LineTriggerKey" ADD VALUE 'FAKE_PURCHASE_REVIEW_OVERDUE_REMINDER' AFTER 'FAKE_PURCHASE_REVIEW_DEADLINE_REMINDER';
ALTER TYPE "LineTriggerKey" ADD VALUE 'SIMPLE_REVIEW_OVERDUE_REMINDER' AFTER 'SIMPLE_REVIEW_DEADLINE_REMINDER';
